.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KPENGINE 1 "November 1, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kpengine \- helper program for kanjipad
.SH SYNOPSIS
.B kanjipad

.SH DESCRIPTION

kpengine is a helper program for kanjipad and is not intended for general use.

.SH SEE ALSO
.BR kanjipad (1)

.SH AUTHOR
KanjiPad was written by Owen Taylor <otaylor@gtk.org>. This manual page was
written by Dafydd Harries <daf@muse.19inch.net> for Debian GNU/Linux but may
be used by others.
